// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	order "mail/internal/handler/order"
	user "mail/internal/handler/user"
	"mail/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/user/:id",
				Handler: user.GetUserHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/order/:id",
				Handler: order.GetOrderHandler(serverCtx),
			},
		},
	)
}
