// Code generated by goctl. DO NOT EDIT.
package types

type GetUserRequest struct {
	Id string `path:"id"`
}

type GetUserResponse struct {
	Name string `json:"name"`
}

type GetOrderRequest struct {
	Id string `path:"id"`
}

type GetOrderResponse struct {
	Order string `json:"order"`
}
